import { StyleSheet } from 'react-native';
import { color } from 'theme/color';

export default StyleSheet.create({
  discover: {
    marginHorizontal: 16,
    marginTop: 33,
    marginBottom: 108,
  },
  title: {
    fontSize: 20,
    fontFamily: 'Epilogue',
    textAlign: 'center',
    lineHeight: 28,
    fontWeight: '700',
    color: color.grayOffWhite,
  },
  description: {
    fontSize: 16,
    fontFamily: 'Epilogue',
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '400',
    color: color.grayBG,
    marginHorizontal: 56,
    marginTop: 16,
  },
  buttonView: {
    marginTop: 39,
    marginBottom: 23,
  },
  itemMargin: {
    marginBottom: 40,
  },
  item: {
    borderRadius: 24,
    backgroundColor: color.grayBody,
  },
  itemCover: {
    marginBottom: 65,
    width: '100%',
    height: 135,
  },
  itemName: {
    fontFamily: 'Epilogue',
    fontWeight: '700',
    fontSize: 24,
    lineHeight: 32,
    color: color.grayOffWhite,
    textAlign: 'center',
  },
  itemDescription: {
    fontFamily: 'Epilogue',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 22,
    color: color.grayBG,
    textAlign: 'center',
    marginHorizontal: 15,
    marginTop: 8,
    marginBottom: 16,
  },
  secondRowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  secondRowFollower: {
    fontFamily: 'Epilogue',
    fontWeight: '700',
    fontSize: 32,
    color: color.grayOffWhite,
    marginLeft: 20,
  },
  secondRowText: {
    fontFamily: 'Epilogue',
    fontWeight: '500',
    fontSize: 16,
    color: color.grayBG,
  },
  secondRowButton: {
    backgroundColor: color.grayTitle,
    borderRadius: 8,
    marginRight: 17,
  },
  secondRowButtonText: {
    fontFamily: 'Epilogue',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    color: color.grayOffWhite,
    paddingHorizontal: 30,
    paddingTop: 9,
    paddingBottom: 7,
  },
  itemAvatar: {
    alignSelf: 'center',
    borderWidth: 4,
    borderRadius: 100,
    borderColor: '#FFFFFF',
    position: 'absolute',
    marginTop: 93,
    width: 93,
    height: 93,
  },
  loadMoreButton: {
    borderRadius: 8,
    borderColor: '#0038F5',
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 35,
  },
  loadMoreButtonText: {
    fontSize: 20,
    fontFamily: 'Epilogue',
    textAlign: 'center',
    paddingVertical: 15,
    color: color.grayOffWhite,
    fontWeight: '700',
  },
});
