import { StyleSheet } from 'react-native';
import { color } from 'theme/color';

export default StyleSheet.create({
  sold: {
    marginTop: 53,
    marginHorizontal: 16,
    marginBottom: 58,
  },
  infoView: {
    marginHorizontal: 18,
    marginTop: 16,
  },
  buttonBorder: {
    borderRadius: 40,
    backgroundColor: color.grayBody,
    alignSelf: 'center',
    marginLeft: 12,
  },
  buttonImage: {
    margin: 11,
  },
  userButton: {
    backgroundColor: color.grayBody,
    borderRadius: 52,
    alignSelf: 'baseline',
    flexDirection: 'row',
  },
  userAvatar: {
    marginRight: 8,
    marginVertical: 4,
    marginLeft: 5,
  },
  userName: {
    fontFamily: 'Epilogue',
    fontSize: 16,
    fontWeight: '700',
    color: color.grayBG,
    alignSelf: 'center',
    paddingRight: 16,
    paddingVertical: 8,
  },
  infoDescription: {
    marginVertical: 11,
    fontFamily: 'Epilogue',
    fontSize: 13,
    fontWeight: '500',
    color: color.grayBG,
    lineHeight: 20,
  },
  hashtagButton: {
    borderRadius: 27,
    borderColor: color.grayPlaceholder,
    borderWidth: 1,
    alignSelf: 'center',
    marginRight: 2,
  },
  hashtagButtonText: {
    fontFamily: 'Epilogue',
    fontSize: 13,
    fontWeight: '500',
    color: color.grayBG,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  shareButton: {
    borderRadius: 16,
    marginTop: 16,
    backgroundColor: color.grayBody,
    paddingVertical: 15,
    paddingHorizontal: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  shareButtonText: {
    fontSize: 16,
    fontFamily: 'Epilogue',
    color: color.grayOffWhite,
    fontWeight: '700',
    lineHeight: 24,
  },
  soldView: {
    borderRadius: 24,
    backgroundColor: color.grayBody,
    marginTop: 36,
    paddingLeft: 17,
  },
  soldFirstRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 51,
    marginBottom: 24,
    paddingTop: 25,
  },
  soldFirstRowTitle: {
    fontSize: 20,
    fontFamily: 'Epilogue',
    color: color.grayBG,
    fontWeight: '400',
    lineHeight: 28,
  },
  soldFirstRowPrice: {
    fontSize: 16,
    fontFamily: 'Epilogue',
    color: color.grayBG,
    fontWeight: '700',
    lineHeight: 24,
  },
  soldFirstRowImage: {
    position: 'absolute',
    right: 0,
    top: 0,
    marginRight: 12,
    marginTop: 11,
  },
  soldSecondRowView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 35,
  },
  soldSecondRowTitle: {
    fontSize: 20,
    fontFamily: 'Epilogue',
    color: color.grayBG,
    fontWeight: '400',
    lineHeight: 28,
    paddingRight: 7,
  },
  soldSecondRowButton: {
    backgroundColor: color.grayLabel,
    borderRadius: 52,
    alignItems: 'center',
    flexDirection: 'row',
  },
  buttonAvatar: {
    marginRight: 8,
    marginVertical: 4,
    marginLeft: 5,
  },
  buttonText: {
    fontFamily: 'Epilogue',
    fontSize: 16,
    fontWeight: '700',
    color: color.grayBG,
    alignSelf: 'center',
    paddingRight: 16,
    paddingVertical: 8,
  },
  activityTitle: {
    fontSize: 20,
    fontFamily: 'Epilogue',
    color: color.grayBG,
    fontWeight: '400',
    lineHeight: 28,
    paddingTop: 26,
  },
  activityButton: {
    borderRadius: 24,
    marginTop: 12,
    backgroundColor: color.grayBody,
    paddingVertical: 15,
    paddingHorizontal: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  activityButtonAvatar: {
    marginRight: 13,
    borderRadius: 24,
  },
  activityButtonTitle: {
    fontSize: 14,
    fontFamily: 'Epilogue',
    color: color.grayOffWhite,
    fontWeight: '700',
    lineHeight: 20,
  },
  activityButtonDate: {
    fontSize: 13,
    fontFamily: 'Epilogue',
    color: color.grayLine,
    fontWeight: '500',
    lineHeight: 20,
  },
  buttonPriceSold: {
    fontSize: 16,
    fontFamily: 'Epilogue',
    color: color.grayLine,
    fontWeight: '700',
    lineHeight: 24,
  },
  buttonPriceBold: {
    fontSize: 16,
    fontFamily: 'Epilogue',
    color: color.grayLine,
    fontWeight: '700',
    lineHeight: 24,
    paddingRight: 3,
  },
  buttonPriceLight: {
    fontSize: 13,
    fontFamily: 'Epilogue',
    color: color.grayInputBG,
    fontWeight: '500',
    lineHeight: 20,
    alignSelf: 'center',
  },
});
