name: "Android Build"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter

jobs:
  build-android:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v2
      
      - name: Fastlane
        run: cd android && fastlane beta

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command

      - name: Build Android ${{inputs.environment == 'release' && 'Release' || 'Debug'}}
        run: |
          cd android && ./gradlew bundle${{inputs.environment == 'release' && 'Release' || 'Debug'}} --no-daemon
      # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FinderUK.aab
          path: "android/app/build/outputs/bundle/release/app-release.aab"
